version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: lapor-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lapor
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    networks:
      - lapor-network

  # LAPOR Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lapor-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/lapor?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production_minimum_32_characters
      JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:3000
      UPLOAD_PATH: uploads
      MAX_FILE_SIZE: 5242880
      DEFAULT_ADMIN_EMAIL: admin@lapor.com
      DEFAULT_ADMIN_PASSWORD: admin123
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb
    networks:
      - lapor-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  uploads_data:
    driver: local

networks:
  lapor-network:
    driver: bridge